name: qbot-messaging
region: nyc
services:
  - name: qbot
    github:
      repo: usdevs/QBotMessaging
      branch: main
      deploy_on_push: true
    build_command: pip install uv && uv sync
    run_command: python main.py
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: BOT_TOKEN
        type: SECRET
        value: ""
