name: qbot-messaging
region: nyc
services:
  - name: qbot
    github:
      repo: usdevs/QBotMessaging
      branch: main
      deploy_on_push: true
    build_command: pip install python-telegram-bot python-dotenv
    run_command: python main.py
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: BOT_TOKEN
        type: SECRET
        value: ""
